"use client"; 

import { useState, useEffect, useRef } from "react";
import Head from "next/head";

const Home = () => {
  const isMountedRef = useRef(null);
  const [display, setDisplay] = useState("");
  const [error, setError] = useState("");
  const [advancedMode, setAdvancedMode] = useState(
    localStorage.getItem("advancedMode") === "true" ? true : false
  );
  const [searchTerm, setSearchTerm] = useState("");
  const [searchResults, setSearchResults] = useState([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (isMountedRef.current) {
      ReactGA.pageview(window.location.pathname);
    } else {
      isMountedRef.current = true;
    }
  }, []);

  useEffect(() => {
    localStorage.setItem("advancedMode", advancedMode);
  }, [advancedMode]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container p-4">
        <h1 className="text-2xl font-geist-sans font-bold underline">Hello world!</h1>
      </div>
    </>
  );
};

export default Home;

const displayError = (error) => {
  console.log(error);
};

const displayResults = (results) => {
  console.log(results);
};